# This workflow will build Speedb on a Mac OS server
#
# This workflow assumes the self hosted runner on a Mac machine is ready.
# The Mac OS server must have all the tools and software required for Speedb building to be installed


name: Build on Ubuntu Arm 

on:
  workflow_call:
    inputs:
      verSion:
        required: true
        type: string
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuArm64 # a test self hosted runner on a vm with MacOS
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'build'
      run: |
        export JAVA_HOME=$(jrunscript -e 'java.lang.System.out.println(java.lang.System.getProperty("java.home"));')
        PORTABLE=1 DEBUG_LEVEL=0 make -j $(nproc) rocksdbjavastatic
    
    - name: 'upload artifacts'    #This step executed only when this workflow is called by another and a version is provided
      if: inputs.verSion != ' '
      run: aws s3 cp java/target/libspeedbjni-linux-aarch64.so s3://spdb-builder/jar_test/v${{ inputs.verSion }}/libspeedbjni-linux-aarch64.so
